project_name: gorter
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gorter
    ldflags:
      - -s -w
      - -X version.Version={{.Version}}
      - -X version.Revision={{.ShortCommit}}
      - -X version.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
release:
  prerelease: auto
